export const WEEKS = [
  {
    number: 1, theme: "The Language of Finance",
    goal: "Understand how money flows through a business.",
    days: [
      { day: "Day 1", topic: "Time Value of Money", type: "Concept",
        desc: "Why a dollar today is worth more than tomorrow. Master NPV and discounting.",
        task: "Calculate NPV of 3 personal decisions: a car loan, a savings plan, an investment.",
        prompts: ["Core logic of discounting future cash flows?", "How would you explain NPV to a non-finance colleague?", "Key formulas to remember:"],
        hints: [
          { l: "Present Value", f: "PV = FV / (1 + r)ⁿ", n: "$1,000 in 5yr at 8% = $681 today." },
          { l: "Future Value", f: "FV = PV × (1 + r)ⁿ", n: "$10k at 7% for 10yr → $19,672." },
          { l: "NPV", f: "NPV = Σ[CFₜ/(1+r)ᵗ] − C₀", n: "NPV > 0 → accept. NPV < 0 → reject." },
          { l: "Annuity PV", f: "PV = PMT × [1−(1+r)⁻ⁿ]/r", n: "Shortcut for equal periodic payments." },
        ]},
      { day: "Day 2", topic: "Case: Amazon's Early Capital Decisions", type: "Case Study",
        desc: "Analyze why Bezos reinvested aggressively in 1998 instead of pursuing profit.",
        task: "Write a 1-page memo: Was Amazon's cash burn justifiable using TVM logic?",
        prompts: ["Amazon's financial position in 1998?", "Was the cash burn justified? Why/why not?", "What would you recommend as CFO?"],
        hints: [
          { l: "NPV", f: "NPV = Σ[CFₜ/(1+r)ᵗ] − Investment", n: "Positive NPV justifies burning cash today." },
          { l: "Payback Period", f: "Payback = Investment / Annual CF", n: "Amazon's was long — was that acceptable?" },
          { l: "Revenue Growth", f: "g = (Rev_t − Rev_{t-1}) / Rev_{t-1}", n: "1998 Amazon grew ~300% YoY." },
        ]},
      { day: "Day 3", topic: "Free Cash Flow & Valuation Basics", type: "Concept",
        desc: "What FCF is, why it matters more than profit, and how to compute it.",
        task: "Download Apple's latest 10-K and compute FCF for the last 3 years.",
        prompts: ["FCF formula vs. net income:", "Apple FCF (Year 1/2/3):", "Key insight from this exercise:"],
        hints: [
          { l: "FCF (quick)", f: "FCF = CFO − CapEx", n: "Fastest method using the cash flow statement." },
          { l: "FCF (full)", f: "FCF = Net Income + D&A − ΔWC − CapEx", n: "Start from net income." },
          { l: "FCF Margin", f: "FCF Margin = FCF / Revenue", n: "Apple's is ~25–28%." },
        ]},
      { day: "Day 4", topic: "Case: Netflix vs. Blockbuster", type: "Case Study",
        desc: "Compare cash flow profiles at the inflection point when Netflix was winning.",
        task: "Build a simple FCF comparison table. Write a 3-bullet investment thesis for Netflix (2005).",
        prompts: ["Netflix vs Blockbuster FCF differences:", "My 3-bullet investment thesis:", "What made Blockbuster structurally fragile?"],
        hints: [
          { l: "FCF", f: "FCF = CFO − CapEx", n: "Netflix improving; Blockbuster crushed by store leases." },
          { l: "Operating Leverage", f: "= Fixed Costs / Total Costs", n: "Blockbuster had enormous fixed costs." },
          { l: "LTV", f: "LTV = ARPU × Margin% × (1/Churn)", n: "Netflix LTV grew as churn fell." },
        ]},
      { day: "Day 5", topic: "WACC", type: "Concept + Practice",
        desc: "How companies set their investment hurdle rate using the cost of all capital.",
        task: "Estimate WACC for a company of your choice using Yahoo Finance data.",
        prompts: ["WACC formula breakdown:", "Company & data inputs:", "What does this WACC say about risk?"],
        hints: [
          { l: "WACC", f: "WACC = (E/V)Re + (D/V)Rd(1−Tc)", n: "E=equity, D=debt, V=E+D." },
          { l: "CAPM", f: "Re = Rf + β(Rm−Rf)", n: "Rf = 10yr Treasury, ERP ~5–6%." },
          { l: "Cost of Debt", f: "Rd = Interest Expense / Total Debt", n: "Multiply by (1−tax rate)." },
        ]},
    ],
  },
  {
    number: 2, theme: "Capital Structure & Leverage",
    goal: "Understand the risk-reward tradeoff of debt financing.",
    days: [
      { day: "Day 1", topic: "Debt vs. Equity Financing", type: "Concept",
        desc: "Modigliani-Miller, tax shields, and why capital structure matters in practice.",
        task: "Compare D/E ratios of 3 companies in different industries. Hypothesize why they differ.",
        prompts: ["Core MM insight:", "D/E ratios & reasons:", "Which industry surprised you most?"],
        hints: [
          { l: "D/E Ratio", f: "D/E = Total Debt / Equity", n: "Airlines 2–5x; Tech often < 0.5x." },
          { l: "Tax Shield", f: "V_L = V_U + Tax Rate × Debt", n: "$1B debt at 25% → $250M shield." },
          { l: "DuPont ROE", f: "ROE = ROA × (Assets/Equity)", n: "Leverage boosts ROE even if ROA flat." },
        ]},
      { day: "Day 2", topic: "Case: Hertz Bankruptcy (2020)", type: "Case Study",
        desc: "How excessive leverage destroyed a 100-year-old company during a demand shock.",
        task: "Reconstruct Hertz's pre-COVID capital structure. At what debt level did it fail?",
        prompts: ["Hertz capital structure (estimated):", "Tipping point — debt/revenue ratio:", "What could management have done differently?"],
        hints: [
          { l: "ICR", f: "ICR = EBIT / Interest Expense", n: "< 1.5x signals distress." },
          { l: "Net Debt/EBITDA", f: "= (Debt − Cash) / EBITDA", n: "Safe: 2–3x. Hertz: 8–10x." },
          { l: "DSCR", f: "DSCR = NOI / Debt Service", n: "< 1.0 = can't cover payments from ops." },
        ]},
      { day: "Day 3", topic: "Leveraged Buyouts", type: "Concept",
        desc: "How PE uses debt to amplify returns — and the full mechanics behind it.",
        task: "Build a simplified LBO for a fictional $10M EBITDA company. Target 20% IRR.",
        prompts: ["LBO mechanics in your words:", "Your model inputs:", "Did you hit 20% IRR?"],
        hints: [
          { l: "Entry EV", f: "EV = EBITDA × Multiple (6–12x)", n: "At 8x / $10M EBITDA = $80M. 70% debt." },
          { l: "Equity IRR", f: "r = (Out/In)^(1/5) − 1", n: "$24M in → $58M out → IRR ≈ 19.3%." },
          { l: "Leverage Check", f: "Entry Leverage = Debt / EBITDA", n: "Lenders allow 4–6x for stable cos." },
        ]},
      { day: "Day 4", topic: "Case: KKR & RJR Nabisco", type: "Case Study",
        desc: "The 'Barbarians at the Gate' deal — largest LBO in history at the time.",
        task: "Identify 3 brilliant and 3 reckless decisions in the KKR deal.",
        prompts: ["3 brilliant decisions:", "3 reckless decisions:", "What would you have done differently?"],
        hints: [
          { l: "Entry Multiple", f: "EV / EBITDA → target < 8–10x", n: "KKR paid ~8.6x on $2.9B EBITDA." },
          { l: "IRR", f: "0 = −Inv + Σ[CFₜ/(1+IRR)ᵗ]", n: "PE targets 20–25% IRR." },
          { l: "Equity Return", f: "= (Exit EV − Debt) / Equity In", n: "Depended on divesting Nabisco brands." },
        ]},
      { day: "Day 5", topic: "Build Your Capital Structure", type: "Assignment",
        desc: "You are CFO of a fictional mid-size company. Design its optimal financing mix.",
        task: "Deliver a 1-page CFO memo recommending a debt/equity split with full rationale.",
        prompts: ["Company scenario:", "Recommended structure & rationale:", "Risks acknowledged to the board:"],
        hints: [
          { l: "Optimal Structure", f: "V = V_unlev + PV(Shield) − PV(Distress)", n: "Balance tax benefits vs. distress costs." },
          { l: "TIE", f: "TIE = EBIT / Interest (target > 3x)", n: "Must cover interest 3x after adding debt." },
          { l: "Credit Leverage", f: "AAA<1x · BBB~2–3x · BB~4–5x", n: "Higher leverage = lower rating = costlier debt." },
        ]},
    ],
  },
  {
    number: 3, theme: "Valuation & Investment Decisions",
    goal: "Master core tools to value businesses.",
    days: [
      { day: "Day 1", topic: "DCF Valuation", type: "Concept + Model",
        desc: "Build a Discounted Cash Flow model from scratch. Understand its assumptions and limits.",
        task: "Value a company using a 5-year DCF with terminal value. Use conservative assumptions.",
        prompts: ["Company & key assumptions:", "DCF output vs market price:", "Where is model most sensitive?"],
        hints: [
          { l: "DCF", f: "Value = Σ[FCFₜ/(1+r)ᵗ] + TV/(1+r)⁵", n: "Project 5yr FCF, discount at WACC." },
          { l: "Terminal Value", f: "TV = FCF₅×(1+g)/(WACC−g)", n: "TV = 60–80% of total. g < WACC always." },
          { l: "Equity Value", f: "Price = (EV + Cash − Debt) / Shares", n: "Bridge from EV to equity." },
        ]},
      { day: "Day 2", topic: "Case: Snap IPO (2017)", type: "Case Study",
        desc: "Was Snap worth $24B at IPO? Build bull and bear scenarios.",
        task: "Build two DCF scenarios for Snap. What growth assumptions drive each?",
        prompts: ["Bull case & implied value:", "Bear case & implied value:", "Was $24B justified?"],
        hints: [
          { l: "ARPU", f: "ARPU = Revenue / DAUs", n: "Snap 2017: ~$1.05 global, $4+ N. America." },
          { l: "EV/Revenue", f: "= Enterprise Value / Revenue", n: "Snap IPO: ~48x vs Facebook ~28x." },
          { l: "DAU Growth", f: "g = (DAU_t − DAU_{t-1}) / DAU_{t-1}", n: "Already slowing at IPO — key driver." },
        ]},
      { day: "Day 3", topic: "Comparable Company Analysis", type: "Concept + Practice",
        desc: "Value a company by comparing to peers using EV/EBITDA, P/E, EV/Revenue.",
        task: "Pick a public company. Build a comps table with 5 peers. Overvalued or undervalued?",
        prompts: ["Target & 5 comps:", "Multiples table (EV/EBITDA, P/E, EV/Rev):", "Conclusion:"],
        hints: [
          { l: "EV", f: "EV = Mkt Cap + Debt − Cash", n: "The acquisition price of the whole business." },
          { l: "EV/EBITDA", f: "= Enterprise Value / EBITDA", n: "Tech: 15–30x · Industrials: 8–12x." },
          { l: "Implied Price", f: "= (Median Multiple × Metric − Debt) / Shares", n: "Apply peer median to your target." },
        ]},
      { day: "Day 4", topic: "Case: Disney Acquires Pixar", type: "Case Study",
        desc: "How Disney valued Pixar at $7.4B in 2006 and what premium they paid.",
        task: "Reverse-engineer the acquisition price. What synergies justify the premium?",
        prompts: ["Pixar standalone DCF (est.):", "Synergies needed to justify $7.4B:", "Was the premium rational?"],
        hints: [
          { l: "Acq. Premium", f: "= (Deal − Pre-Ann. Cap) / Pre-Ann. Cap", n: "Disney paid $7.4B; cap was ~$6.3B pre-rumor." },
          { l: "Synergy NPV", f: "= Σ[Annual Synergies / (1+r)ᵗ]", n: "Parks IP, distribution, shared tech." },
          { l: "Accretion", f: "= (Post EPS − Pre EPS) / Pre EPS", n: "Was the all-stock deal EPS-accretive Y1?" },
        ]},
      { day: "Day 5", topic: "Real Options & Uncertainty", type: "Concept",
        desc: "Why traditional DCF misses value in uncertain, high-growth businesses.",
        task: "Name 3 strategic decisions at a company you know. Re-frame each as a real option.",
        prompts: ["Where does DCF fail to capture value?", "Your 3 real options:", "How does this change your investment lens?"],
        hints: [
          { l: "Option to Expand", f: "Value = Max(NPV_expanded − Inv, 0)", n: "AWS was an option to expand into cloud." },
          { l: "Option to Abandon", f: "Value = Max(Salvage − Continuation, 0)", n: "Phase 1 drug can be sold if it fails." },
          { l: "DCF Gap", f: "True Value = DCF + Option Value (+20–60%)", n: "Largest gap for startups & R&D businesses." },
        ]},
    ],
  },
  {
    number: 4, theme: "Corporate Finance in Action",
    goal: "Apply everything to real executive decisions.",
    days: [
      { day: "Day 1", topic: "Dividends & Share Buybacks", type: "Concept",
        desc: "When should companies return cash? The dividend irrelevance debate.",
        task: "Research Apple's buyback program. Calculate EPS impact over 5 years.",
        prompts: ["Dividend irrelevance argument:", "Apple buyback data & EPS impact:", "Value creation or financial engineering?"],
        hints: [
          { l: "EPS Impact", f: "New EPS = Net Income / (Shares − Repurchased)", n: "Apple retired ~40% of shares since 2012." },
          { l: "Buyback Yield", f: "= $ Repurchased / Mkt Cap", n: "Apple ~3–4% annually." },
          { l: "TSR", f: "= (Price Gain + Dividends) / Initial Price", n: "Full picture of shareholder return." },
        ]},
      { day: "Day 2", topic: "Case: Microsoft Acquires Activision", type: "Case Study",
        desc: "A $69B deal. Analyze the strategic rationale, structure, and market reaction.",
        task: "Would you approve this deal as a board member? Write a 1-page dissent or endorsement.",
        prompts: ["Strategic rationale:", "Financing structure & implications:", "Board vote — approve or dissent?"],
        hints: [
          { l: "EV/EBITDA", f: "= Enterprise Value / EBITDA", n: "MSFT paid ~23x vs. peers at 12–18x." },
          { l: "Synergy", f: "= ΔRevenue × Margin × (1/WACC)", n: "5M new Game Pass subs = $900M/yr." },
          { l: "ROIC", f: "= NOPAT / Invested Capital", n: "Must exceed WACC (~8%) to create value." },
        ]},
      { day: "Day 3", topic: "Financial Distress & Restructuring", type: "Concept",
        desc: "What happens when a company cannot service debt. Restructuring options.",
        task: "Study a successful restructuring (e.g., GM 2009). Map their path.",
        prompts: ["Company & nature of distress:", "Steps taken:", "What made it succeed or fail?"],
        hints: [
          { l: "Altman Z", f: "Z=1.2X₁+1.4X₂+3.3X₃+0.6X₄+X₅ (<1.8=distress)", n: "X₃=EBIT/Assets is most predictive." },
          { l: "DSCR", f: "= NOI / (Principal + Interest)", n: "< 1.0 = can not pay from operations." },
          { l: "D→E Conversion", f: "New Eq% = Debt Converted/(Debt+Eq)", n: "Reduces cash interest burden." },
        ]},
      { day: "Day 4", topic: "Integrated Simulation", type: "Capstone Assignment",
        desc: "You are CFO: raise debt, issue equity, acquire, or return cash?",
        task: "Build a 3-year financial plan for a given company profile. Present to the board.",
        prompts: ["Company scenario & metrics:", "3-year plan & rationale:", "Board narrative:"],
        hints: [
          { l: "Cash Waterfall", f: "Ending Cash = Begin + CFO − CapEx ± Financing", n: "Build all 3 years." },
          { l: "Funding Gap", f: "= Capital Needed − Internal FCF", n: "$150M needed − $80M FCF → $70M gap." },
          { l: "Dilution", f: "= New Shares / (Old + New)", n: "$50M at $20/sh on 10M shares → 20% dilution." },
        ]},
      { day: "Day 5", topic: "Reflection & Self-Assessment", type: "Review",
        desc: "Consolidate learning. Identify gaps. Prepare for Financial Reporting & Control.",
        task: "Write 'Finance I Lessons Learned' — 5 concepts you can apply at work immediately.",
        prompts: ["5 concepts I can apply at work:", "2 biggest gaps to revisit:", "How my thinking has changed:"],
        hints: []},
    ],
  },
];

export type Week = typeof WEEKS[0];
export type Day = Week["days"][0];

export const TYPE_COLORS: Record<string, { bg: string; tx: string; bd: string }> = {
  "Concept":             { bg: "#e8f4fd", tx: "#1a5276", bd: "#2980b9" },
  "Case Study":          { bg: "#fef9e7", tx: "#7d6608", bd: "#f39c12" },
  "Assignment":          { bg: "#fdf2f8", tx: "#6c3483", bd: "#8e44ad" },
  "Concept + Practice":  { bg: "#e8f8f5", tx: "#1a5c4a", bd: "#27ae60" },
  "Concept + Model":     { bg: "#e8f8f5", tx: "#1a5c4a", bd: "#27ae60" },
  "Capstone Assignment": { bg: "#fdf5e6", tx: "#784212", bd: "#e67e22" },
  "Review":              { bg: "#f4f6f7", tx: "#424949", bd: "#95a5a6" },
};
